FROM golang:1.12.0-alpine3.9 AS builder
RUN apk --update add --no-cache git gcc musl-dev \
&& go get -u github.com/go-delve/delve/cmd/dlv \
&& mkdir -p /debug/ \
&& mkdir -p /go/pkg/
WORKDIR /debug/

EXPOSE 3000 40000

ENTRYPOINT ["dlv", "debug", "--listen=:40000", "--headless=true", "--api-version=2", "--log"]



